version: "3.9"

services:
  ng:
    build: 
        context: .
        dockerfile: Dockerfile.dev
    image: annotator-ui-dev:0.0.1
    user: $UID:$GID
    command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes: 
      - ./:/app/

